version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/myApp/proyecto_Control_de_Cambios/controladorNew
hooks:
  ApplicationStop:
    - location: /stop_server.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: /start_server.sh
      timeout: 900
      runas: root
